name: Test, Build and Deploy to Raspberry Pi

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Run test coverage (if available)
        run: npm run test:coverage || echo "Coverage not available, skipping..."
        continue-on-error: true

  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Raspberry
    needs: test
    name: Build and Deploy to Raspberry Pi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          # Use package-lock.json to key the cache. This improves cache hits.
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up date and tag environment variables
        run: |
          echo "IMAGE_TAG=$(date +'%Y%m%d')-rasp" >> $GITHUB_ENV
          echo "COMMIT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push AMD64 image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --tag ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:latest-amd64 \
            --tag ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.IMAGE_TAG }}-amd64 \
            --tag ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.COMMIT_SHA }}-amd64 \
            --push .

      - name: Build and push ARM64 image (with retry)
        id: arm64_build
        continue-on-error: true
        run: |
          # Retry ARM64 build up to 2 times with exponential backoff
          for attempt in 1 2; do
            echo "🔄 ARM64 build attempt $attempt/2"
            if docker buildx build \
              --platform linux/arm64 \
              --cache-from=type=local,src=/tmp/.buildx-cache \
              --cache-to=type=local,dest=/tmp/.buildx-cache \
              --tag ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:latest-arm64 \
              --tag ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.IMAGE_TAG }}-arm64 \
              --tag ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.COMMIT_SHA }}-arm64 \
              --push .; then
              echo "✅ ARM64 build succeeded on attempt $attempt"
              echo "arm64_success=true" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "❌ ARM64 build failed on attempt $attempt"
              if [ $attempt -lt 2 ]; then
                echo "⏳ Waiting 30 seconds before retry..."
                sleep 30
              fi
            fi
          done
          echo "❌ All ARM64 build attempts failed"
          echo "arm64_success=false" >> $GITHUB_OUTPUT
          exit 1

      - name: Create and push multi-platform manifest
        if: steps.arm64_build.outcome == 'success' && steps.arm64_build.outputs.arm64_success == 'true'
        run: |
          # Create manifest for latest
          docker buildx imagetools create \
            --tag ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:latest \
            ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:latest-amd64 \
            ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:latest-arm64
          
          # Create manifest for date tag
          docker buildx imagetools create \
            --tag ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.IMAGE_TAG }} \
            ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.IMAGE_TAG }}-amd64 \
            ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.IMAGE_TAG }}-arm64
          
          # Create manifest for commit tag
          docker buildx imagetools create \
            --tag ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.COMMIT_SHA }} \
            ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.COMMIT_SHA }}-amd64 \
            ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.COMMIT_SHA }}-arm64

      - name: Create AMD64-only manifest (fallback)
        if: steps.arm64_build.outcome == 'failure' || steps.arm64_build.outputs.arm64_success == 'false'
        run: |
          echo "⚠️ ARM64 build failed, creating AMD64-only images"
          
          # Tag AMD64 images as the main tags
          docker buildx imagetools create \
            --tag ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:latest \
            ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:latest-amd64
          
          docker buildx imagetools create \
            --tag ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.IMAGE_TAG }} \
            ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.IMAGE_TAG }}-amd64
          
          docker buildx imagetools create \
            --tag ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.COMMIT_SHA }} \
            ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:${{ env.COMMIT_SHA }}-amd64

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.RASPBERRY_HOST }}
          username: ${{ secrets.RASPBERRY_USER }}
          key: ${{ secrets.RASPBERRY_SSH_KEY }}
          port: ${{ secrets.RASPBERRY_PORT || 22 }}
          script: |
            # Stop and remove existing container
            docker stop sporty-leagues || true
            docker rm sporty-leagues || true
            
            # Remove old images (keep last 3)
            docker images ${{ secrets.DOCKER_USERNAME }}/sporty-leagues --format "table {{.Tag}}" | grep -v TAG | tail -n +4 | xargs -I {} docker rmi ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:{} || true
            
            # Pull latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:latest
            
            # Run new container
            docker run -d \
              --name sporty-leagues \
              --restart unless-stopped \
              -p 8080:80 \
              --health-cmd="curl -f http://127.0.0.1/health || exit 1" \
              --health-interval=30s \
              --health-timeout=10s \
              --health-retries=3 \
              ${{ secrets.DOCKER_USERNAME }}/sporty-leagues:latest
            
            # Wait for container to be healthy
            echo "Waiting for container to be healthy..."
            timeout 60 bash -c 'until docker inspect --format="{{.State.Health.Status}}" sporty-leagues | grep -q healthy; do sleep 2; done' || echo "Container health check timeout"
            
            # Show container status
            docker ps -a --filter name=sporty-leagues
            echo "Deployment completed!"

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.RASPBERRY_HOST }}
          username: ${{ secrets.RASPBERRY_USER }}
          key: ${{ secrets.RASPBERRY_SSH_KEY }}
          port: ${{ secrets.RASPBERRY_PORT || 22 }}
          script: |
            # Test application health
            if curl -f http://127.0.0.1:8080/health; then
              echo "✅ Application is healthy and responding!"
            else
              echo "❌ Application health check failed!"
              exit 1
            fi
            
            # Show resource usage
            echo "Container resource usage:"
            docker stats sporty-leagues --no-stream

      - name: Notify deployment success
        if: success()
        run: |
          if [[ "${{ steps.arm64_build.outputs.arm64_success }}" == "true" ]]; then
            echo "🎉 Sporty Leagues successfully deployed to Raspberry Pi with multi-platform support!"
            echo "🏗️ Built for: AMD64 + ARM64"
          else
            echo "🎉 Sporty Leagues successfully deployed to Raspberry Pi!"
            echo "⚠️ Built for: AMD64 only (ARM64 build failed)"
          fi
          echo "🔗 Application URL: http://${{ secrets.RASPBERRY_HOST }}:8080"
          echo "📊 Docker Hub: https://hub.docker.com/r/${{ secrets.DOCKER_USERNAME }}/sporty-leagues"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Deployment failed! Check the logs above for details."
          if [[ "${{ steps.arm64_build.outputs.arm64_success }}" == "false" ]]; then
            echo "💡 Note: ARM64 build failed due to network timeout. This is common in GitHub Actions."
            echo "💡 Consider using separate ARM64 runners or building locally if multi-platform support is critical."
          fi
          exit 1
